# =========================================================
# HYPRLAND MAIN CONFIG (ORQUESTADOR)
# =========================================================

# ---------------------------------------------------------
# VARIABLES DE ENTORNO
# ---------------------------------------------------------
source = ~/.config/hypr/conf/env.conf

# ---------------------------------------------------------
# VARIABLES DE PROGRAMAS
# ---------------------------------------------------------
source = ~/.config/hypr/conf/variables.conf

# ---------------------------------------------------------
# MONITORES
# ---------------------------------------------------------
source = ~/.config/hypr/conf/monitors.conf

# ---------------------------------------------------------
# INPUT
# ---------------------------------------------------------
source = ~/.config/hypr/conf/input.conf

# ---------------------------------------------------------
# LAYOUT / GENERAL BEHAVIOR
# ---------------------------------------------------------
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/layout.conf

# ---------------------------------------------------------
# DECORACIÓN
# ---------------------------------------------------------
source = ~/.config/hypr/conf/decoration.conf

# ---------------------------------------------------------
# ANIMACIONES
# ---------------------------------------------------------
source = ~/.config/hypr/conf/animations.conf

# ---------------------------------------------------------
# GESTOS
# ---------------------------------------------------------
source = ~/.config/hypr/conf/gestures.conf

# ---------------------------------------------------------
# WORKSPACES
# ---------------------------------------------------------
source = ~/.config/hypr/workspaces.conf

# ---------------------------------------------------------
# BINDS (ATAJOS)
# ---------------------------------------------------------
source = ~/.config/hypr/conf/binds.conf

# ---------------------------------------------------------
# AUTOSTART
# ---------------------------------------------------------
source = ~/.config/hypr/conf/autostart.conf

# ---------------------------------------------------------
# DISPOSITIVOS
# ---------------------------------------------------------
source = ~/.config/hypr/conf/devices.conf

# ---------------------------------------------------------
# TEMA / COLORES
# ---------------------------------------------------------
source = ~/.config/hypr/mocha.conf