# =========================================================
# AUTOSTART
# =========================================================
# Programas y servicios lanzados al iniciar Hyprland

# Exporta variables Wayland/DBus
# Necesario para applets y tray
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Bluetooth tray
exec-once = blueman-applet

# NetworkManager tray
exec-once = nm-applet --indicator

# Script custom para control de volumen
exec-once = python3 ~/.config/custom_scripts/keyboard_wheel_control.py

# Inicializa sistema de wallpapers
exec-once = swww init

# Wallpaper usando waypaper
exec-once = waypaper --restore

# Ags para control center
exec-once = ags run ~/.config/ags/app.ts

# Barra superior
exec-once = waybar
