

# =========================================================
# DECORACIÓN
# =========================================================

decoration {

    # Redondeado ventanas
    rounding = 5

    # Blur transparente
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}