# =========================================================
# DISPOSITIVOS
# =========================================================
# Configuración específica teclado Epomaker

device {
    name = "royuan-epomaker-th80-se-consumer-control"
    enabled = true
    kb_layout = us
}

device {
    name = "royuan-epomaker-th80-se-consumer-control-1"
    enabled = true
    kb_layout = us
}
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
cursor {
    no_hardware_cursors = false
}
xwayland {
    force_zero_scaling = true
}
