

# =========================================================
# CONFIGURACIÓN GENERAL
# =========================================================

general {

    # Espacio entre ventanas
    gaps_in = 5

    # Espacio exterior respecto pantalla
    gaps_out = 5

    # Grosor del borde
    border_size = 2

    # Color borde activo
    col.active_border = rgba(545773ee) rgba(545773ee) 45deg

    # Color borde inactivo
    col.inactive_border = rgba(595959aa)

    # Layout tiling
    layout = dwindle

    # Desactivar tearing
    allow_tearing = false
}
