# =========================================================
# GESTOS TOUCHPAD
# =========================================================

gestures {

    # 3 dedos izquierda = siguiente workspace
    gesture = 3, left, workspace, r+1

    # 3 dedos derecha = workspace anterior
    gesture = 3, right, workspace, r-1
}
