# =========================================================
# INPUT
# =========================================================
# Configuración de teclado y ratón

input {

    # Layout del teclado
    kb_layout = us

    # Sigue el foco del ratón
    follow_mouse = 1

    # Sensibilidad del ratón
    sensitivity = 0

    # Configuración touchpad
    touchpad {
        natural_scroll = no
    }
}
