# =========================================================
# LAYOUT DWINDLE
# =========================================================

dwindle {

    # Mantiene divisiones al reorganizar ventanas
    preserve_split = yes
}