# =========================================================
# MONITORES
# =========================================================
# monitor = NOMBRE,resolucion@hz,posicion,escala

# Monitor principal
monitor = DP-2,2560x1440@144,0x0,1

# Monitor secundario vertical
# transform,3 = rotación 270°
monitor = HDMI-A-1,1920x1080@60,2560x0,1
#,transform,3