# =========================================================
# VARIABLES DE PROGRAMAS
# =========================================================

# Terminal por defecto
$terminal = kitty

# Explorador de archivos
$fileManager = nautilus

# Launcher de aplicaciones
$menu = rofi -show drun -show-icons -theme ~/.local/share/rofi/themes/rounded-blue-dark.rasi

# Tecla SUPER/WINDOWS
$mainMod = SUPER
